name: bert_env
dependencies:
  # The python interpreter version.
  # Currently Azure ML only supports 3.5.2 and later.
- python=3.6
- nb_conda==2.2.0
- tornado==4.5.3
- cudatoolkit==9.0
- tensorflow-gpu==1.10.0

- pip:
    # Required packages for AzureML execution, history, and data preparation.
  - papermill==0.14.1
  - python-dotenv==0.10.1
  #- Pillow==5.2.0
  - torch==1.0.1.post2
  #- torchvision==0.2.2.post3
  - tensorboardX==1.6
  #- opencv-python==4.1.0.25
  #- h5py==2.9.0
  #- wget==3.2
  #- matplotlib==2.2.2
  #- aiohttp==3.3.2
  #- toolz==0.9.0
  #- pytorch-pretrained-bert
  - tqdm==4.23.4
  - boto3
  - requests
  - regex
  - scipy
  - sklearn
  #- azure-cli==2.0.41
  #- keras==2.2.0
  #- azureml-sdk[notebooks, contrib]==1.0.21
